# -*- coding: utf-8 -*-
"""Face detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qiCaN31uzIWNkf2qQBe6qjdf8xBHTx8I
"""

import cv2

classifier = cv2.CascadeClassifier("/content/drive/My Drive/haarcascade_frontalface_default.xml")

pixel = cv2.VideoCapture(0)
address = 'http://25.16.189.12:8080/'
pixel.open(address)



faces  = classifier.detectMultiScale(pixel)

for face in faces:
  x, y, width, height = face
  X1,y1 = x+width, y+height
  cv2.rectangle (pixel, (x,y), (X1,y1), (0,255,0), 5)

import matplotlib.pyplot as plt
plt.figure()
plt.imshow(pixel)
plt.show()





